# Generated by Django 5.2.1 on 2025-05-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User3056',
        ),
    ]
