# Generated by Django 5.2.1 on 2025-05-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_rename_user_user3056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user3056',
            name='Confirm_password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
