# Generated by Django 5.2.1 on 2025-05-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_user3056_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user3056',
            name='Confirm_password',
        ),
    ]
