# Generated by Django 5.2.1 on 2025-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_remove_user3056_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user3056',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
