# Generated by Django 5.2.1 on 2025-05-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='cate_id',
            new_name='cid',
        ),
    ]
