# Generated by Django 5.2.1 on 2025-05-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_rename_cate_id_sub_category_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='name',
            new_name='sub_name',
        ),
    ]
