# Generated by Django 5.2.1 on 2025-05-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_rename_name_sub_category_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_name',
            new_name='name',
        ),
    ]
