# Generated by Django 5.2.1 on 2025-05-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0010_rename_sub_name_sub_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('price', models.IntegerField()),
                ('del_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('des', models.TextField()),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.categories')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.sub_category')),
            ],
        ),
    ]
