# Generated by Django 5.2.1 on 2025-05-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0012_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.price'),
        ),
    ]
