# Generated by Django 5.2.1 on 2025-06-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0017_add_to_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_to_wishlist',
        ),
    ]
