# Generated by Django 5.2.1 on 2025-06-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0019_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='total_price',
        ),
    ]
