# Generated by Django 5.2.1 on 2025-06-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0021_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
