# Generated by Django 5.2.1 on 2025-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0025_alter_billingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
