# Generated by Django 5.2.1 on 2025-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0028_orderitem_quantity_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantity_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_order',
            field=models.IntegerField(blank=True, max_length=90, null=True),
        ),
    ]
