# Generated by Django 5.2.1 on 2025-06-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0031_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
