# Generated by Django 5.2.1 on 2025-06-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0033_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
