# Generated by Django 5.2.1 on 2025-06-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0034_rename_user_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eapp.order'),
            preserve_default=False,
        ),
    ]
