# Generated by Django 5.2.1 on 2025-06-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0036_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
