# Generated by Django 5.2.1 on 2025-06-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0038_order_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
