# Generated by Django 5.2.1 on 2025-06-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0039_remove_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
