# Generated by Django 5.2.1 on 2025-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0043_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
