# Generated by Django 5.2.1 on 2025-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0048_review_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user3056',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
