# Generated by Django 5.2.1 on 2025-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0049_user3056_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user3056',
            name='profile_image',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
